#!/bin/bash
set -euo pipefail

# ZeroTeir Infrastructure Setup
# One-command deployment of AWS infrastructure + Headscale bootstrap
#
# Usage: ./setup.sh [--profile AWS_PROFILE] [--region REGION] [--dry-run]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/terraform"
SSH_KEY_NAME="zeroteir-key"
SSH_KEY_PATH="$HOME/.ssh/$SSH_KEY_NAME.pem"

# Defaults
AWS_PROFILE="${AWS_PROFILE:-default}"
AWS_REGION="us-east-1"
DRY_RUN=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --profile) AWS_PROFILE="$2"; shift 2 ;;
        --region)  AWS_REGION="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --help|-h)
            echo "Usage: ./setup.sh [--profile AWS_PROFILE] [--region REGION] [--dry-run]"
            echo ""
            echo "Options:"
            echo "  --profile   AWS CLI profile name (default: \$AWS_PROFILE or 'default')"
            echo "  --region    AWS region (default: us-east-1)"
            echo "  --dry-run   Show what would be done without making changes"
            exit 0
            ;;
        *) error "Unknown option: $1"; exit 1 ;;
    esac
done

export AWS_PROFILE
export AWS_DEFAULT_REGION="$AWS_REGION"

echo ""
echo "============================================"
echo "  ZeroTeir Infrastructure Setup"
echo "============================================"
echo "  Profile: $AWS_PROFILE"
echo "  Region:  $AWS_REGION"
echo "  Dry Run: $DRY_RUN"
echo "============================================"
echo ""

# Step 1: Check prerequisites
info "Checking prerequisites..."

check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        error "$1 is not installed. Install with: $2"
        exit 1
    fi
    ok "$1 found: $(command -v "$1")"
}

check_cmd terraform "brew install hashicorp/tap/terraform"
check_cmd aws "brew install awscli"

# Verify AWS credentials
info "Verifying AWS credentials..."
if ! aws sts get-caller-identity &>/dev/null; then
    error "AWS credentials not configured for profile '$AWS_PROFILE'"
    echo "  Run: aws configure --profile $AWS_PROFILE"
    exit 1
fi
ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
ok "AWS account: $ACCOUNT_ID (profile: $AWS_PROFILE)"

# Step 2: Create SSH key pair if needed
info "Checking SSH key pair..."
if aws ec2 describe-key-pairs --key-names "$SSH_KEY_NAME" &>/dev/null 2>&1; then
    ok "SSH key pair '$SSH_KEY_NAME' already exists in AWS"
    if [[ ! -f "$SSH_KEY_PATH" ]]; then
        warn "Local key file not found at $SSH_KEY_PATH"
        warn "You may need to recreate the key pair if you lost the private key"
    fi
else
    info "Creating SSH key pair '$SSH_KEY_NAME'..."
    if [[ "$DRY_RUN" == "true" ]]; then
        info "[DRY RUN] Would create SSH key pair and save to $SSH_KEY_PATH"
    else
        aws ec2 create-key-pair \
            --key-name "$SSH_KEY_NAME" \
            --query 'KeyMaterial' \
            --output text > "$SSH_KEY_PATH"
        chmod 600 "$SSH_KEY_PATH"
        ok "SSH key pair created and saved to $SSH_KEY_PATH"
    fi
fi

# Step 3: Auto-detect public IP
info "Detecting your public IP for admin_ip..."
ADMIN_IP=$(curl -s https://checkip.amazonaws.com 2>/dev/null || echo "")
if [[ -n "$ADMIN_IP" ]]; then
    ADMIN_IP="${ADMIN_IP}/32"
    ok "Public IP: $ADMIN_IP"
else
    warn "Could not detect public IP, using 0.0.0.0/0 (open to all)"
    ADMIN_IP="0.0.0.0/0"
fi

# Step 4: Generate terraform.tfvars
info "Generating terraform.tfvars..."
TFVARS_FILE="$TERRAFORM_DIR/terraform.tfvars"

if [[ "$DRY_RUN" == "true" ]]; then
    info "[DRY RUN] Would write terraform.tfvars with:"
    echo "  ssh_key_name = \"$SSH_KEY_NAME\""
    echo "  aws_region   = \"$AWS_REGION\""
    echo "  admin_ip     = \"$ADMIN_IP\""
else
    cat > "$TFVARS_FILE" <<EOF
# Generated by setup.sh on $(date -Iseconds)
ssh_key_name         = "$SSH_KEY_NAME"
aws_region           = "$AWS_REGION"
admin_ip             = "$ADMIN_IP"
instance_type        = "t3.micro"
idle_timeout_minutes = 60
EOF
    ok "Written to $TFVARS_FILE"
fi

# Step 5: Terraform init & apply
info "Initializing Terraform..."
cd "$TERRAFORM_DIR"

if [[ "$DRY_RUN" == "true" ]]; then
    info "[DRY RUN] Would run: terraform init"
    info "[DRY RUN] Would run: terraform apply -auto-approve"
else
    terraform init -input=false
    ok "Terraform initialized"

    info "Deploying infrastructure (this takes ~2 minutes)..."
    terraform apply -auto-approve -input=false
    ok "Infrastructure deployed"
fi

# Step 6: Extract outputs
if [[ "$DRY_RUN" == "true" ]]; then
    info "[DRY RUN] Would extract terraform outputs"
    info "[DRY RUN] Would wait for Headscale API key in SSM"
    echo ""
    echo "============================================"
    echo "  DRY RUN COMPLETE"
    echo "============================================"
    exit 0
fi

info "Extracting configuration..."
ELASTIC_IP=$(terraform output -raw elastic_ip)
API_ENDPOINT=$(terraform output -raw api_endpoint)
API_KEY=$(terraform output -raw api_key)
INSTANCE_ID=$(terraform output -raw instance_id)
HEADSCALE_URL=$(terraform output -raw headscale_url)

ok "Elastic IP:    $ELASTIC_IP"
ok "API Endpoint:  $API_ENDPOINT"
ok "Instance ID:   $INSTANCE_ID"
ok "Headscale URL: $HEADSCALE_URL"

# Step 7: Wait for Headscale API key in SSM
info "Waiting for Headscale to bootstrap and store API key in SSM..."
info "(Instance needs to boot + run cloud-init, ~3-5 minutes)"

# First start the instance if it's stopped
INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids "$INSTANCE_ID" --query 'Reservations[0].Instances[0].State.Name' --output text)
if [[ "$INSTANCE_STATE" != "running" ]]; then
    info "Starting instance..."
    aws ec2 start-instances --instance-ids "$INSTANCE_ID" >/dev/null
    aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
    ok "Instance is running"
fi

HEADSCALE_API_KEY=""
MAX_WAIT=300  # 5 minutes
WAITED=0
INTERVAL=15

while [[ $WAITED -lt $MAX_WAIT ]]; do
    HEADSCALE_API_KEY=$(aws ssm get-parameter \
        --name "/zeroteir/headscale-api-key" \
        --with-decryption \
        --query 'Parameter.Value' \
        --output text 2>/dev/null || echo "")

    if [[ -n "$HEADSCALE_API_KEY" && "$HEADSCALE_API_KEY" != "None" ]]; then
        ok "Headscale API key retrieved from SSM"
        break
    fi

    WAITED=$((WAITED + INTERVAL))
    info "  Waiting... ($WAITED/${MAX_WAIT}s)"
    sleep $INTERVAL
done

if [[ -z "$HEADSCALE_API_KEY" || "$HEADSCALE_API_KEY" == "None" ]]; then
    warn "Timed out waiting for Headscale API key"
    warn "Cloud-init may still be running. You can retrieve it later with:"
    echo "  aws ssm get-parameter --name /zeroteir/headscale-api-key --with-decryption --query Parameter.Value --output text --profile $AWS_PROFILE"
    HEADSCALE_API_KEY="(pending - check SSM later)"
fi

# Step 8: Output configuration
echo ""
echo "============================================"
echo "  ZeroTeir Setup Complete!"
echo "============================================"
echo ""
echo "Enter these values in the ZeroTeir app Settings > Connection tab:"
echo ""
echo "  Lambda API Endpoint:  $API_ENDPOINT"
echo "  Lambda API Key:       $API_KEY"
echo "  Headscale URL:        $HEADSCALE_URL"
echo "  Headscale API Key:    $HEADSCALE_API_KEY"
echo ""
echo "SSH access:"
echo "  ssh -i $SSH_KEY_PATH ubuntu@$ELASTIC_IP"
echo ""
echo "Estimated monthly cost:"
echo "  Persistent: ~\$4.29/mo (EIP + 8GB EBS)"
echo "  Compute:    ~\$0.0104/hr (t3.micro, only when connected)"
echo ""
echo "============================================"

# Save config to a local file for reference
CONFIG_FILE="$SCRIPT_DIR/.zeroteir-config"
cat > "$CONFIG_FILE" <<EOF
# ZeroTeir Configuration - Generated $(date -Iseconds)
# DO NOT COMMIT THIS FILE
LAMBDA_API_ENDPOINT=$API_ENDPOINT
LAMBDA_API_KEY=$API_KEY
HEADSCALE_URL=$HEADSCALE_URL
HEADSCALE_API_KEY=$HEADSCALE_API_KEY
ELASTIC_IP=$ELASTIC_IP
INSTANCE_ID=$INSTANCE_ID
SSH_KEY_PATH=$SSH_KEY_PATH
AWS_PROFILE=$AWS_PROFILE
AWS_REGION=$AWS_REGION
EOF
ok "Config saved to $CONFIG_FILE"
