name: SecretTunnel
options:
  bundleIdPrefix: com.secrettunnel
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  WireGuardKit:
    path: LocalPackages/wireguard-apple

targets:
  SecretTunnel:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/SecretTunnel
      - path: Shared
    resources:
      - Resources/Assets.xcassets
    info:
      path: Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleIdentifier: com.secrettunnel.vpn
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.secrettunnel.vpn
      CODE_SIGN_ENTITLEMENTS: Resources/SecretTunnel.entitlements
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_LSUIElement: true
      ENABLE_HARDENED_RUNTIME: true
      DEVELOPMENT_TEAM: 7552UR9ZVD
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Automatic
          # When Developer ID cert is installed, change to:
          # CODE_SIGN_STYLE: Manual
          # CODE_SIGN_IDENTITY: "Developer ID Application: Conor McMillan (7552UR9ZVD)"
    dependencies:
      - target: SecretTunnelExtension
        embed: true
      - sdk: NetworkExtension.framework

  SecretTunnelExtension:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: SecretTunnelExtension
      - path: Shared
    info:
      path: SecretTunnelExtension/Info.plist
      properties:
        CFBundleIdentifier: com.secrettunnel.vpn.tunnel
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.secrettunnel.vpn.tunnel
      CODE_SIGN_ENTITLEMENTS: SecretTunnelExtension/SecretTunnelExtension.entitlements
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ENABLE_HARDENED_RUNTIME: true
      DEVELOPMENT_TEAM: 7552UR9ZVD
      LIBRARY_SEARCH_PATHS: "$(inherited) $(SRCROOT)/LocalPackages/wireguard-apple/Sources/WireGuardKitGo"
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
          LIBRARY_SEARCH_PATHS: "$(inherited) $(SRCROOT)/LocalPackages/wireguard-apple/Sources/WireGuardKitGo"
        Release:
          CODE_SIGN_STYLE: Automatic
          # When Developer ID cert is installed, change to:
          # CODE_SIGN_STYLE: Manual
          # CODE_SIGN_IDENTITY: "Developer ID Application: Conor McMillan (7552UR9ZVD)"
          LIBRARY_SEARCH_PATHS: "$(inherited) $(SRCROOT)/LocalPackages/wireguard-apple/Sources/WireGuardKitGo"
    dependencies:
      - package: WireGuardKit
      - sdk: NetworkExtension.framework

  SecretTunnelTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Tests/SecretTunnelTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.secrettunnel.vpn.tests
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 7552UR9ZVD
      GENERATE_INFOPLIST_FILE: true
    dependencies:
      - target: SecretTunnel
