name: ZeroTeir
options:
  bundleIdPrefix: com.zeroteir
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

packages:
  WireGuardKit:
    path: LocalPackages/wireguard-apple

targets:
  ZeroTeir:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/ZeroTeir
      - path: Shared
    resources:
      - Resources/Assets.xcassets
    info:
      path: Resources/Info.plist
      properties:
        LSUIElement: true
        CFBundleIdentifier: com.zeroteir.vpn
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    entitlements:
      path: Resources/ZeroTeir.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zeroteir.vpn
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_LSUIElement: true
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 7552UR9ZVD
    dependencies:
      - target: ZeroTeirTunnel
        embed: true
      - sdk: NetworkExtension.framework

  ZeroTeirTunnel:
    type: app-extension
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: ZeroTeirTunnel
      - path: Shared
    info:
      path: ZeroTeirTunnel/Info.plist
      properties:
        CFBundleIdentifier: com.zeroteir.vpn.tunnel
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider
    entitlements:
      path: ZeroTeirTunnel/ZeroTeirTunnel.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.zeroteir.vpn.tunnel
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 7552UR9ZVD
      LIBRARY_SEARCH_PATHS: "$(inherited) $(SRCROOT)/LocalPackages/wireguard-apple/Sources/WireGuardKitGo"
    dependencies:
      - package: WireGuardKit
      - sdk: NetworkExtension.framework
